//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_SuperHeroes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acompanantes
    {
        public int SuperheroeID { get; set; }
        public int AcompananteID { get; set; }
        public int AgrupacionesID { get; set; }
    
        public virtual Agrupaciones Agrupaciones { get; set; }
        public virtual Superheroes Superheroes { get; set; }
    }
}
